FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.24.3@sha256:81bf5927dc91aefb42e2bc3a5abdbe9bb3bae8ba8b107e2a4cf43ce3402534c6 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.22@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-github-comment"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-github-comment"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-github-comment"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-github-comment"

COPY --from=build /src/dist/wp-github-comment /bin/wp-github-comment
ENTRYPOINT ["/bin/wp-github-comment"]
